#!/bin/bash
# SketchyBar config (AeroSpace 連動・モダンネオン版)
# Reference: https://felixkratz.github.io/SketchyBar

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar position=top \
                 height=32 \
                 blur_radius=40 \
                 color=0xaa0a0a14 \
                 padding_left=8 \
                 padding_right=8 \
                 margin=0 \
                 corner_radius=0

##### Default item appearance #####
default=(
  padding_left=3
  padding_right=3
  icon.font="Hack Nerd Font:Bold:14.0"
  label.font="Hack Nerd Font:Bold:12.0"
  icon.color=0xffe0e0ff
  label.color=0xffe0e0ff
  icon.padding_left=6
  icon.padding_right=6
  label.padding_left=4
  label.padding_right=8
  background.height=24
  background.corner_radius=6
)
sketchybar --default "${default[@]}"

##### Apple logo (left) #####
sketchybar --add item apple_logo left \
           --set apple_logo \
               icon= \
               icon.font="Hack Nerd Font:Bold:16.0" \
               icon.color=0xffff5fff \
               icon.padding_left=8 \
               icon.padding_right=8 \
               label.drawing=off

##### Separator #####
sketchybar --add item sep1 left \
           --set sep1 \
               icon= \
               icon.color=0x66ffffff \
               label.drawing=off

##### AeroSpace Workspaces (left) #####
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9")
for i in "${!SPACE_ICONS[@]}"; do
  sid=$((i+1))
  sketchybar --add item space.$sid left \
             --set space.$sid \
                 icon="${SPACE_ICONS[i]}" \
                 icon.padding_left=10 \
                 icon.padding_right=10 \
                 background.color=0x33ffffff \
                 background.drawing=on \
                 background.corner_radius=8 \
                 background.height=22 \
                 label.drawing=off \
                 click_script="aerospace workspace $sid" \
                 script="$PLUGIN_DIR/aerospace.sh $sid" \
             --subscribe space.$sid aerospace_workspace_change
done

##### Separator #####
sketchybar --add item sep2 left \
           --set sep2 \
               icon= \
               icon.color=0x66ffffff \
               icon.padding_left=8 \
               icon.padding_right=8 \
               label.drawing=off

##### Front App (left) #####
sketchybar --add item front_app left \
           --set front_app \
               icon.drawing=off \
               label.font="Hack Nerd Font:Bold:12.0" \
               label.color=0xffff5fff \
               script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Right items #####
sketchybar --add item clock right \
           --set clock \
               update_freq=10 \
               icon=󰥔 \
               icon.color=0xff8aff80 \
               background.color=0x22ffffff \
               background.drawing=on \
               script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume \
               icon.color=0xff80c0ff \
               background.color=0x22ffffff \
               background.drawing=on \
               script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery \
               update_freq=120 \
               icon.color=0xffffc080 \
               background.color=0x22ffffff \
               background.drawing=on \
               script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Initial render #####
sketchybar --update
